name: Popeye Leskó Kalandtúrák
timezone: Europe/Budapest

defaults:
  -
    scope:
      path: "" # minden oldalnak ez az alapértelmezés, ha üres a `path`
    values:
      layout: turakeret
      mainid: main
      title: Popeye Leskó Kalandtúrák
