name: Popeye Leskó Kalandtúrák
timezone: Europe/Budapest
plugins:
- jekyll-redirect-from

defaults:
  - 
    scope:
      path: "" # minden oldalnak ez az alapértelmezés, ha üres a `path`
    values:
      layout: weblapkeret
      mainid: main
      title: Popeye Leskó Kalandtúrák
      themecolor: #743
      #themecolor: #a84
      #themecolor: #eb8

collections:
  turak:
    permalink: /:path
    output: true
    layout: turakeret
  

#markdown: kramdown
#theme: minima
theme: jekyll-theme-midnight

# http://shopify.github.io/liquid/filters/date/
minima:
  date_format: "%b %-d, %Y"

show_excerpts: true
facebook_username: http://popeyelesko.hu
google_analytics: UA-28587585-1
