# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

backendB:
  name: github
  repo: PopeyeLesko/popeyelesko.github.io    # Path to Github repository
  branch: master    # Branch to update

media_folder: "/kepek/+fel"

collections:
- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "Blog" # Used in the UI
  folder: "_posts"
  create: true # Allow users to create new documents in this collection
  fields: # The fields for each document, usually in front matter
  - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Dátum", name: "date", widget: "datetime"}
  - {label: "Kép", name: "kep", widget: "image"}
  - {label: "Kategória", name: "category", widget: "list", default: ["sztori"]}
  - {label: "Body", name: "body", widget: "markdown"}

