---
hide_body: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: turakeret
- name: mainid
  label: Mainid
  type: text
  hidden: false
  default: main
- name: title
  label: Title
  type: text
  hidden: false
  default: Popeye Leskó Kalandtúrák
